# Generated by Django 4.2.7 on 2023-12-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ex007', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
